apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-users
  labels:
    app: udagram-users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-users
  template:
    metadata:
      labels:
        app: udagram-users
    spec:
      containers:
      - name: udagram-users
        image: meddy672/udagramusers
        ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 3